# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 02:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajos',
            name='funciones',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name='Funciones',
        ),
    ]
