# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 02:58
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170813_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidades',
            options={'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='imagenes',
            options={'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='info_pagina',
            options={'verbose_name_plural': 'Info de la Pagina'},
        ),
        migrations.AlterModelOptions(
            name='trabajos',
            options={'verbose_name_plural': 'Trabajos'},
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='funciones',
            field=ckeditor.fields.RichTextField(default='<ul><li></li></ul>'),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='tipo',
            field=models.CharField(choices=[(1, 'APP'), (2, 'WEB')], default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='trabajos',
            name='video',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
