# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170813_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajos',
            name='tipo',
            field=models.CharField(choices=[(1, 'APP'), (2, 'WEB')], max_length=3),
        ),
    ]
