# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170814_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajos',
            name='tipo',
            field=models.CharField(choices=[('aplicacion', 'APP'), ('web', 'WEB')], max_length=3),
        ),
    ]
