# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170814_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidades',
            name='imagen',
        ),
        migrations.AddField(
            model_name='habilidades',
            name='tipo',
            field=models.CharField(choices=[('lan', 'Programming Language'), ('app', 'Aplicacion'), ('web', 'Web')], default='null', max_length=3),
        ),
    ]
