# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170814_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajos',
            name='abreviacion',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
