# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-29 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20180829_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajos',
            name='color',
            field=models.CharField(default='null', max_length=6),
        ),
    ]
