# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-30 12:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_trabajos_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_pagina',
            name='home_desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
